from .keyboard_start import keyboard_start
from .keyboard_analyse import keyboard_analyse
from .keyboard_library import keyboard_library
from .keyboard_filters import keyboard_filters
from .keyboard_filters_players import keyboard_filters_player
from .keyboard_filters_ages import keyboard_filters_age
from .keyboard_filters_years import keyboard_filters_year
from .keyboard_filters_manufactories import keyboard_filters_manufactory
from .keyboard_filter_mainmenu import keyboard_filter_main_menu
from .keyboard_main import keyboard_main_menu
